<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>GpxWorldMap</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Config\" />
    <Folder Include="Models\" />
    <Folder Include="Input\" />
    <Folder Include="Server\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="bin\Debug\net8.0\gpxworldmap.config.json" />
    <None Remove="bin\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="bin\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="bin\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Features/*/*.html" CopyToOutputDirectory="PreserveNewest"/>
    <Content Update="Features\Heatmap\heatmap.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Features\Linemap\linemap.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Features\WeeklyMileage\weeklymileage.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Controls/Templates/*.js" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Index/*.html" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
