<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>GpxWorldMap</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Config\" />
    <Folder Include="Models\" />
    <Folder Include="Readers\" />
    <Folder Include="Rendering\" />
    <Folder Include="Server\" />
    <Folder Include="Shared\" />
  </ItemGroup>

</Project>
